# Generated by Django 3.2.12 on 2022-04-16 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'ordering': ['-date_joined'], 'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AddField(
            model_name='user',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, default='NG', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries_plus.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your Name/Company Representative'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Name of Company')),
                ('phone', models.CharField(blank=True, help_text='eg: 07076879898', max_length=11, null=True, unique=True, verbose_name='Mobile Number')),
                ('office_phone', models.CharField(blank=True, help_text='eg: 07076879898', max_length=11, null=True, unique=True, verbose_name='Office Number')),
                ('office_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Address')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State/Province')),
                ('postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries_plus.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('card_type', models.CharField(blank=True, choices=[('MasterCard', 'MasterCard'), ('Visa', 'Visa'), ('American Express', 'American Express')], max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry_month', models.PositiveIntegerField(blank=True, null=True)),
                ('card_expiry_year', models.PositiveIntegerField(blank=True, null=True)),
                ('card_cvv', models.PositiveIntegerField(blank=True, null=True)),
                ('saved_card', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Details',
                'verbose_name_plural': 'Card Details',
                'ordering': ['-created'],
            },
        ),
    ]
