# Generated by Django 3.1.13 on 2021-09-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210921_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
