# Generated by Django 3.1.13 on 2021-09-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notif_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_info',
        ),
    ]
